update:
  period: 5s
debezium:
  log:
    level: ${quarkus.log.level}

quarkus:
  http:
    port: 4563
  tls:
    trust-all: true
  datasource:
    db-kind: postgresql
  flyway:
    baseline-on-migrate: true
    migrate-at-start: true
  log:
    category:
      "io.debezium":
        level: ${debezium.log.level}
"%prod":
  quarkus:
    kubernetes-config:
      enabled: true
      config-maps: crypto-app-config

"%dev":
  debezium:
    log:
      level: DEBUG
  quarkus:
    kubernetes-client:
      devservices:
        enabled: false
    flyway:
      clean-at-start: true

"%test":
  quarkus:
    flyway:
      clean-at-start: true