apiVersion: v1
kind: ConfigMap
metadata:
  name: crypto-app-config
data:
  quarkus.datasource.jdbc.url: 'jdbc:postgresql://postgresql:5432/coincap'
  quarkus.datasource.username: 'postgres'
  quarkus.datasource.password: 'postgres'
  quarkus.datasource.db-kind: 'postgresql'
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.11.0
  labels:
    app.kubernetes.io/name: debezium-crypto-app
    app.kubernetes.io/managed-by: quarkus
  name: debezium-crypto-app
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: debezium-crypto-app
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: debezium-crypto-app-view
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: view
subjects:
  - kind: ServiceAccount
    name: debezium-crypto-app
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.11.0
  labels:
    app.kubernetes.io/name: debezium-crypto-app
    app.kubernetes.io/managed-by: quarkus
  name: debezium-crypto-app
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 4563
  selector:
    app.kubernetes.io/name: debezium-crypto-app
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.11.0
  labels:
    app.kubernetes.io/name: debezium-crypto-app
    app.kubernetes.io/managed-by: quarkus
  name: debezium-crypto-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: debezium-crypto-app
  template:
    metadata:
      annotations:
        app.quarkus.io/quarkus-version: 3.11.0
      labels:
        app.kubernetes.io/managed-by: quarkus
        app.kubernetes.io/name: debezium-crypto-app
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: quay.io/jcechace/dbz-crypto-app:native-latest
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/live
              port: 4563
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          name: debezium-crypto-app
          ports:
            - containerPort: 4563
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/ready
              port: 4563
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          startupProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/started
              port: 4563
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
      serviceAccountName: debezium-crypto-app
